### ISSUE TITLE
Crash on string_client.py

### ISSUE THREAD

**Issue by ehsteve** [Spacebrew/pySpacebrew#5]
I get the following error (including the weird formatting in case it is useful).

```
Exception in thread Thread-1:
                                      Traceback (most recent call last):
                                                                          File "/Users/user/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                                                                                                                                        self.run()
            File "/Users/user/anaconda/lib/python2.7/threading.py", line 763, in run
                                                                                            self.__target(*self.__args, **self.__kwargs)
                                                                                                                                          File "/Users/user/Downloads/pySpacebrew/examples/pySpacebrew/spacebrew.py", line 121, in run
                                                                      self.run()
                                                                                  File "/Users/user/Downloads/pySpacebrew/examples/pySpacebrew/spacebrew.py", line 111, in run
              self.ws = websocket.WebSocketApp( "ws://{0}:{1}".format(self.server,self.port),
                                                                                             AttributeError: 'module' object has no attribute 'WebSocketApp'
```

when I quit the program I get the following error

```
Traceback (most recent call last):
  File "string_client.py", line 81, in <module>
    brew.publish('chat outgoing',cur_line)
  File "/Users/user/Downloads/pySpacebrew/examples/pySpacebrew/spacebrew.py", line 104, in publish
    self.ws.send(json.dumps(message))
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by robotconscience** [comment]
@quinkennedy any ideas?
